mongo:
    image: mongo:latest

dev:
  image: node:0.10-slim
  links:
    - mongo
  working_dir: /usr/src/app
  volumes:
    - ".:/usr/src/app"
  command: "npm run watch"
  environment:
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=info
