dev:
  image: node:0.10-slim
  working_dir: /usr/src/app
  volumes:
    - ".:/usr/src/app"
  command: "npm run watch"
  environment:
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=info
    - NPM_PACKAGE_CONFIG_UNSAFE_PERM=true
    - NPM_CONFIG_UNSAFE_PERM=true
